auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/ingress-nginx/controller:v1.1.1: yangchao1/ingress-nginx-controller:v1.1.1
  k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1: yangchao1/ingress-nginx-kube-webhook-certgen:v1.1.1
