auth:
  registry.cn-beijing.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/ingress-nginx/controller: yc-gcr-rsync/ingress-nginx-controller
  k8s.gcr.io/ingress-nginx/kube-webhook-certgen: yc-gcr-rsync/ingress-nginx-kube-webhook-certgen
